spring:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: false